//! Embed the built dashboard into the binary.
//!
//! The dashboard is compiled by pnpm/vite into `dashboard/dist`, then baked into
//! the binary at build time. There is no runtime dependency on Node, no asset
//! directory to ship alongside the binary, and no filesystem read per request —
//! which is what makes the single-binary deployment story hold.
//!
//! Walking the directory and generating a table of `include_bytes!` calls (rather
//! than adding an embedding crate) keeps the runtime dependency set unchanged and
//! means a missing `dashboard/dist` is a build-time *decision* we control: the
//! binary still builds and serves an explanation instead of assets.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn main() {
    println!("cargo:rerun-if-changed=dashboard/dist");
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=dashboard/index.html");

    let manifest_dir = PathBuf::from(
        std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is set by cargo"),
    );
    let dist = manifest_dir.join("dashboard").join("dist");
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR is set by cargo"));

    let mut assets: Vec<(String, PathBuf)> = Vec::new();
    if dist.is_dir() {
        collect(&dist, &dist, &mut assets);
    }
    assets.sort_by(|a, b| a.0.cmp(&b.0));

    let mut generated = String::new();
    generated.push_str("// @generated by build.rs — do not edit.\n");
    generated.push_str("pub static ASSETS: &[crate::web::EmbeddedAsset] = &[\n");
    for (rel, abs) in &assets {
        let _ = writeln!(
            generated,
            "    crate::web::EmbeddedAsset {{ path: {rel:?}, content_type: {:?}, bytes: include_bytes!({abs:?}), immutable: {} }},",
            content_type(rel),
            is_immutable(rel),
        );
    }
    generated.push_str("];\n");

    let dest = out_dir.join("dashboard_assets.rs");
    std::fs::write(&dest, generated).expect("write generated asset table");

    // A build that silently ships zero assets would be discovered only at
    // runtime, in production. Say so now instead.
    if assets.is_empty() {
        println!(
            "cargo:warning=dashboard/dist is missing: the binary will serve a placeholder page. \
             Run `pnpm --dir dashboard build` to embed the dashboard."
        );
    } else {
        println!(
            "cargo:warning=embedding {} dashboard asset(s) from dashboard/dist",
            assets.len()
        );
    }
}

/// Recursively collect files, keyed by their path relative to `root` with `/`
/// separators (so the key is URL-shaped on every platform).
fn collect(root: &Path, dir: &Path, out: &mut Vec<(String, PathBuf)>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect(root, &path, out);
        } else if let Ok(rel) = path.strip_prefix(root) {
            let key = rel
                .components()
                .map(|c| c.as_os_str().to_string_lossy().into_owned())
                .collect::<Vec<_>>()
                .join("/");
            out.push((key, path));
        }
    }
}

/// Map a file extension to a content type.
///
/// An unknown extension is served as a download rather than guessed at, so the
/// browser cannot be tricked into executing something we did not intend.
fn content_type(path: &str) -> &'static str {
    match path.rsplit('.').next().unwrap_or("") {
        "html" => "text/html; charset=utf-8",
        "js" | "mjs" => "text/javascript; charset=utf-8",
        "css" => "text/css; charset=utf-8",
        "json" | "map" => "application/json; charset=utf-8",
        "svg" => "image/svg+xml",
        "png" => "image/png",
        "jpg" | "jpeg" => "image/jpeg",
        "webp" => "image/webp",
        "ico" => "image/x-icon",
        "woff" => "font/woff",
        "woff2" => "font/woff2",
        "txt" => "text/plain; charset=utf-8",
        _ => "application/octet-stream",
    }
}

/// Whether a file may be cached forever.
///
/// Vite emits content-hashed names for everything under `assets/`, so a given
/// URL's bytes never change and it can be cached immutably. `index.html` is the
/// opposite — it names the current hashes and must be revalidated, or a rolling
/// update would keep serving a page pointing at deleted assets.
fn is_immutable(path: &str) -> bool {
    path.starts_with("assets/")
}
