//! Static serving for the embedded dashboard.
//!
//! The dashboard is a single-page app baked into the binary by `build.rs`. Serving
//! is a table lookup by exact path: there is no path joining, so directory
//! traversal is not possible by construction rather than by filtering.
//!
//! Routing order matters and is enforced in `main`: API and proxy routes are
//! declared first, and this module owns only the fallback. The SPA fallback
//! therefore returns `index.html` for unknown *pages* without ever masking a
//! genuine 404 from `/v1/*` or `/api/*`.

use axum::{
    body::Body,
    http::{StatusCode, Uri, header},
    response::{IntoResponse, Response},
};

/// One embedded asset.
pub struct EmbeddedAsset {
    /// Path relative to the asset root, with `/` separators. Never starts with `/`.
    pub path: &'static str,
    pub content_type: &'static str,
    pub bytes: &'static [u8],
    /// Whether the URL is content-addressed and may be cached forever.
    pub immutable: bool,
}

// Generated by build.rs from `dashboard/dist`. Empty when the dashboard has not
// been built, in which case a placeholder is served instead.
include!(concat!(env!("OUT_DIR"), "/dashboard_assets.rs"));

/// Look up an asset by its URL path.
fn lookup(path: &str) -> Option<&'static EmbeddedAsset> {
    // Requests are always rooted. Trimming *all* leading slashes would quietly
    // accept `//index.html` as `index.html`, so exactly one is removed and any
    // further empty segment is rejected below.
    let key = path.strip_prefix('/')?;
    // The root path means the app entry point.
    let key = if key.is_empty() { "index.html" } else { key };

    // Reject anything that is not a plain relative path. Embedded lookups already
    // cannot escape the table, but refusing these keeps URL handling obvious.
    if key
        .split('/')
        .any(|seg| seg == ".." || seg == "." || seg.is_empty())
    {
        return None;
    }

    ASSETS.iter().find(|a| a.path == key)
}

/// Build a response for an embedded asset.
fn asset_response(asset: &'static EmbeddedAsset) -> Response {
    let cache_control = if asset.immutable {
        // Content-hashed name: this exact URL's bytes never change.
        "public, max-age=31536000, immutable"
    } else {
        // Entry documents must be revalidated, or a rolling update keeps serving
        // a page that points at assets the new version deleted.
        "no-cache"
    };

    Response::builder()
        .status(StatusCode::OK)
        .header(header::CONTENT_TYPE, asset.content_type)
        .header(header::CACHE_CONTROL, cache_control)
        // The dashboard calls the API on the same origin and needs no embedding.
        .header("X-Content-Type-Options", "nosniff")
        .header("Referrer-Policy", "same-origin")
        // The dashboard is self-contained: no scripts, styles, frames or
        // connections from anywhere else. This is what keeps a compromised
        // dependency from phoning home through the operator's browser.
        .header(
            "Content-Security-Policy",
            "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; \
             img-src 'self' data:; connect-src 'self'; font-src 'self'; object-src 'none'; \
             base-uri 'none'; frame-ancestors 'none'",
        )
        .body(Body::from(asset.bytes))
        .unwrap_or_else(|_| internal_error())
}

fn internal_error() -> Response {
    (StatusCode::INTERNAL_SERVER_ERROR, "internal error").into_response()
}

/// Serve an exact asset, or fall through to the SPA entry point.
pub async fn serve(uri: Uri) -> Response {
    let path = uri.path();

    if let Some(asset) = lookup(path) {
        return asset_response(asset);
    }

    // An asset-looking request that is not embedded is a genuine miss. Returning
    // index.html here would hand a script tag a page of HTML.
    if looks_like_asset(path) {
        return not_found();
    }

    match lookup("index.html") {
        Some(index) => asset_response(index),
        None => not_built(),
    }
}

/// Whether a path is requesting a static file rather than an app route.
fn looks_like_asset(path: &str) -> bool {
    let last = path.rsplit('/').next().unwrap_or("");
    last.contains('.')
}

/// Fallback for unmatched routes: the API surface must 404 as JSON, not as HTML.
pub async fn fallback(uri: Uri) -> Response {
    let path = uri.path();

    if path.starts_with("/api/") || path.starts_with("/v1/") {
        return json_not_found(path);
    }

    serve(uri).await
}

fn json_not_found(path: &str) -> Response {
    let body = serde_json::json!({
        "error": {
            "message": format!("Unknown endpoint: {path}"),
            "type": "invalid_request_error",
            "code": "not_found",
        }
    });

    (
        StatusCode::NOT_FOUND,
        [(header::CONTENT_TYPE, "application/json")],
        serde_json::to_string(&body).unwrap_or_else(|_| r#"{"error":{}}"#.to_string()),
    )
        .into_response()
}

fn not_found() -> Response {
    (StatusCode::NOT_FOUND, "Not Found").into_response()
}

/// Served when the binary was built without a dashboard bundle.
fn not_built() -> Response {
    const PAGE: &str = r#"<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<title>Partner Portal</title>
<style>
  body { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; margin: 4rem auto;
         max-width: 42rem; line-height: 1.6; color: #111; }
  code { background: #f2f2f2; padding: .15rem .35rem; border-radius: 3px; }
</style></head>
<body>
<h1>Partner Portal</h1>
<p>This binary was built without an embedded dashboard.</p>
<p>The API is running normally. Build the dashboard to embed it:</p>
<p><code>pnpm --dir dashboard install &amp;&amp; pnpm --dir dashboard build</code></p>
<p>then rebuild the binary.</p>
</body></html>"#;

    Response::builder()
        .status(StatusCode::SERVICE_UNAVAILABLE)
        .header(header::CONTENT_TYPE, "text/html; charset=utf-8")
        .header(header::CACHE_CONTROL, "no-store")
        .body(Body::from(PAGE))
        .unwrap_or_else(|_| internal_error())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_lookup_rejects_traversal_segments() {
        assert!(lookup("/../etc/passwd").is_none());
        assert!(lookup("/assets/../../secret").is_none());
        assert!(lookup("/./index.html").is_none());
        assert!(lookup("//index.html").is_none());
    }

    #[test]
    fn test_lookup_maps_root_to_index() {
        // Whether index.html is embedded depends on the build, but the mapping
        // itself must be consistent.
        let root = lookup("/");
        let index = lookup("/index.html");
        assert_eq!(root.is_some(), index.is_some());
    }

    #[test]
    fn test_asset_detection() {
        assert!(looks_like_asset("/assets/index-abc123.js"));
        assert!(looks_like_asset("/favicon.svg"));
        assert!(!looks_like_asset("/"));
        assert!(!looks_like_asset("/dashboard"));
    }

    #[test]
    fn test_embedded_paths_are_relative_and_unique() {
        let mut seen = std::collections::HashSet::new();
        for asset in ASSETS {
            assert!(
                !asset.path.starts_with('/'),
                "embedded paths must be relative: {}",
                asset.path
            );
            assert!(
                !asset.path.contains(".."),
                "embedded paths must not contain traversal: {}",
                asset.path
            );
            assert!(seen.insert(asset.path), "duplicate asset: {}", asset.path);
        }
    }

    #[test]
    fn test_embedded_assets_are_non_empty_and_typed() {
        for asset in ASSETS {
            assert!(!asset.bytes.is_empty(), "{} is empty", asset.path);
            assert_ne!(
                asset.content_type, "application/octet-stream",
                "{} has an unmapped content type",
                asset.path
            );
        }
    }

    #[tokio::test]
    async fn test_api_paths_404_as_json_not_html() {
        let response = fallback(Uri::from_static("/api/does-not-exist")).await;
        assert_eq!(response.status(), StatusCode::NOT_FOUND);
        assert_eq!(
            response.headers().get(header::CONTENT_TYPE).unwrap(),
            "application/json"
        );
    }

    #[tokio::test]
    async fn test_v1_paths_404_as_json() {
        let response = fallback(Uri::from_static("/v1/embeddings")).await;
        assert_eq!(response.status(), StatusCode::NOT_FOUND);
        assert_eq!(
            response.headers().get(header::CONTENT_TYPE).unwrap(),
            "application/json"
        );
    }

    #[tokio::test]
    async fn test_unknown_asset_extension_is_not_served_as_html() {
        // A missing .js must not receive an HTML page with a 200.
        let response = serve(Uri::from_static("/assets/missing-xyz.js")).await;
        if lookup("/assets/missing-xyz.js").is_none() {
            assert_eq!(response.status(), StatusCode::NOT_FOUND);
        }
    }

    #[tokio::test]
    async fn test_unknown_app_route_falls_back_to_entry_point() {
        let response = serve(Uri::from_static("/dashboard/requests")).await;
        // With no dashboard embedded this is the placeholder; with one it is the
        // SPA entry. Either way it must not be a bare 404.
        assert_ne!(response.status(), StatusCode::NOT_FOUND);
    }
}
